language: r
sudo: true
cache: packages
warnings_are_errors: false
r_build_args: #--verbose
r:
 - oldrel
 - release
 - devel # Devtools fails to download in developer mode for some reason
os:
 - linux
 - osx

before_install:
 - if [[ "$TRAVIS_OS_NAME" = 'linux' ]]; then sudo apt-get install libxml2-dev && sudo apt-get install libcurl4-openssl-dev; fi
