language: r
sudo: false
cache: packages
r:
 - oldrel
 - release
 - devel # Devtools fails to download in developer mode for some reason

before_install:
 - if [[ "$TRAVIS_OS_NAME" = 'linux' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi
os:
 - linux
 - osx
