language: r
sudo: true
cache: packages
warnings_are_errors: false
r_build_args: #--verbose
r:
 - oldrel
 - release
 - devel # Devtools fails to download in developer mode for some reason
os:
 - linux
 - osx

before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100
  - mkdir -p ~/.R
  - echo "VkVSPS01CkNDPWdjYyQoVkVSKSAtc3RkPWMxMSAKQ1hYPWcrKyQoVkVSKQpTSExJQl9DWFhMRD1nKyskKFZFUikKRkM9Z2ZvcnRyYW4KRjc3PWdmb3J0cmFuCg==" | base64 -d > ~/.R/Makevars
  - cat ~/.R/Makevars
# The base 64 string is
#VER=-5
#CC=gcc$(VER) -std=c11
#CXX=g++$(VER)
#SHLIB_CXXLD=g++$(VER)
#FC=gfortran
#F77=gfortran
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9

env:
  - COMPILER=gcc-4.9
